targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          - lib/**.dart
        options:
          build_extensions:
            'lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generated/{{file}}.g.dart'
            # '^lib/{{path}}/{{file}}.dart': 'lib/generated/{{file}}.g.dart'
      json_serializable:
        options:
          # build_extensions:
          #   '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'